CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" text NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" text NOT NULL,
        "FullName" character varying(100) NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "DateOfBirth" timestamp with time zone,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE TABLE "AssessmentModules" (
        "Id" uuid NOT NULL,
        "CreatedByUser" character varying(200) NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_AssessmentModules" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE TABLE "Banners" (
        "Id" uuid NOT NULL,
        "Type" integer NOT NULL,
        "Title" character varying(200) NOT NULL,
        "Content" character varying(5000) NOT NULL,
        "ShowToAuthenticatedUsersOnly" boolean NOT NULL,
        "IsDismissible" boolean NOT NULL,
        "CreatedByUser" character varying(200) NOT NULL,
        "UpdatedByUser" character varying(200) NOT NULL,
        "StartDateUtc" timestamp with time zone NOT NULL,
        "EndDateUtc" timestamp with time zone,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Banners" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE TABLE "ExamTakers" (
        "Id" text NOT NULL,
        "Email" character varying(254),
        "DateOfBirth" timestamp with time zone,
        "NormalizedEmail" character varying(254),
        "FullName" character varying(100),
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ExamTakers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE TABLE "Groups" (
        "Id" uuid NOT NULL,
        "Title" character varying(200) NOT NULL,
        "NormalizedTitle" character varying(200) NOT NULL,
        "Description" character varying(5000) NOT NULL,
        "WaitModuleCompletion" boolean NOT NULL,
        "IsMemberOrderLocked" boolean NOT NULL,
        "UpdatedByUserId" character varying(200) NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        "CreatedByUser" character varying(200) NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Groups" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE TABLE "LogEntries" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Timestamp" timestamp with time zone NOT NULL,
        "Level" character varying(50) NOT NULL,
        "Category" character varying(255),
        "Message" text NOT NULL,
        "Exception" text,
        "UserId" character varying(450),
        "UserEmail" character varying(450),
        "RequestId" character varying(100),
        CONSTRAINT "PK_LogEntries" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE TABLE "MessageTemplates" (
        "Id" uuid NOT NULL,
        "Name" character varying(100) NOT NULL,
        "Subject" character varying(300) NOT NULL,
        "Body" character varying(10000) NOT NULL,
        CONSTRAINT "PK_MessageTemplates" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE TABLE "Pages" (
        "Id" uuid NOT NULL,
        "Type" integer NOT NULL,
        "Title" character varying(256) NOT NULL,
        "Body" character varying(20480) NOT NULL,
        "JsonData" character varying(20480) NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "CreatedBy" character varying(200) NOT NULL,
        "UpdatedBy" character varying(200),
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Pages" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE TABLE "SystemSettings" (
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_SystemSettings" PRIMARY KEY ("Name")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE TABLE "UserConfigurations" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Type" integer NOT NULL,
        "DataJson" text NOT NULL,
        CONSTRAINT "PK_UserConfigurations" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" text NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" text NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE TABLE "AssessmentModuleVersions" (
        "Id" uuid NOT NULL,
        "Title" character varying(200) NOT NULL,
        "NormalizedTitle" character varying(200) NOT NULL,
        "Description" character varying(5000) NOT NULL,
        "Version" integer NOT NULL,
        "IsPublished" boolean NOT NULL,
        "PassingScorePercentage" integer NOT NULL,
        "DurationInMinutes" integer NOT NULL,
        "CreatedByUser" character varying(200) NOT NULL,
        "UpdatedByUser" character varying(200) NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "AssessmentModuleId" uuid NOT NULL,
        CONSTRAINT "PK_AssessmentModuleVersions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AssessmentModuleVersions_AssessmentModules_AssessmentModule~" FOREIGN KEY ("AssessmentModuleId") REFERENCES "AssessmentModules" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE TABLE "Assignments" (
        "Id" uuid NOT NULL,
        "Title" character varying(200) NOT NULL,
        "NormalizedTitle" character varying(200) NOT NULL,
        "Description" character varying(5000),
        "StartDateUtc" timestamp with time zone NOT NULL,
        "EndDateUtc" timestamp with time zone NOT NULL,
        "ShowResultsImmediately" boolean NOT NULL,
        "RandomizeQuestions" boolean NOT NULL,
        "RandomizeAnswers" boolean NOT NULL,
        "IsPublished" boolean NOT NULL,
        "GroupId" uuid NOT NULL,
        "CreatedByUser" character varying(256) NOT NULL,
        "UpdatedByUser" character varying(256),
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_Assignments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Assignments_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES "Groups" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE TABLE "GroupMembers" (
        "Id" uuid NOT NULL,
        "GroupId" uuid NOT NULL,
        "OrderNumber" integer NOT NULL,
        "AssessmentModuleId" uuid NOT NULL,
        CONSTRAINT "PK_GroupMembers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_GroupMembers_AssessmentModules_AssessmentModuleId" FOREIGN KEY ("AssessmentModuleId") REFERENCES "AssessmentModules" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_GroupMembers_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES "Groups" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE TABLE "AssessmentQuestions" (
        "Id" uuid NOT NULL,
        "Text" character varying(5000) NOT NULL,
        "Order" integer NOT NULL,
        "Type" integer NOT NULL,
        "AssessmentModuleVersionId" uuid NOT NULL,
        CONSTRAINT "PK_AssessmentQuestions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AssessmentQuestions_AssessmentModuleVersions_AssessmentModu~" FOREIGN KEY ("AssessmentModuleVersionId") REFERENCES "AssessmentModuleVersions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE TABLE "StaticFiles" (
        "Id" uuid NOT NULL,
        "FileUrl" character varying(500) NOT NULL,
        "AssessmentModuleId" uuid NOT NULL,
        "Label" text,
        "UploadedAtUtc" timestamp with time zone NOT NULL,
        "IsModuleLevelFile" boolean NOT NULL,
        "AssessmentModuleVersionEntityId" uuid,
        CONSTRAINT "PK_StaticFiles" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_StaticFiles_AssessmentModuleVersions_AssessmentModuleVersio~" FOREIGN KEY ("AssessmentModuleVersionEntityId") REFERENCES "AssessmentModuleVersions" ("Id"),
        CONSTRAINT "FK_StaticFiles_AssessmentModules_AssessmentModuleId" FOREIGN KEY ("AssessmentModuleId") REFERENCES "AssessmentModules" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE TABLE "ExamTakerAssignments" (
        "Id" uuid NOT NULL,
        "AssignmentId" uuid NOT NULL,
        "ExamTakerId" text NOT NULL,
        "ExamTakerDisplayName" text NOT NULL,
        CONSTRAINT "PK_ExamTakerAssignments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ExamTakerAssignments_Assignments_AssignmentId" FOREIGN KEY ("AssignmentId") REFERENCES "Assignments" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE TABLE "AssessmentPossibleAnswers" (
        "Id" uuid NOT NULL,
        "Order" integer NOT NULL,
        "Text" character varying(1000) NOT NULL,
        "IsCorrect" boolean NOT NULL,
        "QuestionId" uuid NOT NULL,
        CONSTRAINT "PK_AssessmentPossibleAnswers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AssessmentPossibleAnswers_AssessmentQuestions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES "AssessmentQuestions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE TABLE "QuestionEntityStaticFileEntity" (
        "AssociatedStaticFilesId" uuid NOT NULL,
        "QuestionsId" uuid NOT NULL,
        CONSTRAINT "PK_QuestionEntityStaticFileEntity" PRIMARY KEY ("AssociatedStaticFilesId", "QuestionsId"),
        CONSTRAINT "FK_QuestionEntityStaticFileEntity_AssessmentQuestions_Question~" FOREIGN KEY ("QuestionsId") REFERENCES "AssessmentQuestions" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_QuestionEntityStaticFileEntity_StaticFiles_AssociatedStatic~" FOREIGN KEY ("AssociatedStaticFilesId") REFERENCES "StaticFiles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE TABLE "ModuleProgress" (
        "Id" uuid NOT NULL,
        "QuestionRandomizationSeed" uuid,
        "AnswerRandomizationSeed" uuid,
        "HasStarted" boolean NOT NULL,
        "DurationInMinutes" integer NOT NULL,
        "StartedAtUtc" timestamp with time zone,
        "CompletedAtUtc" timestamp with time zone,
        "ExamTakerAssignmentId" uuid NOT NULL,
        "ExamTakerId" text NOT NULL,
        "GroupMemberId" uuid NOT NULL,
        "AssessmentModuleVersionId" uuid NOT NULL,
        CONSTRAINT "PK_ModuleProgress" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ModuleProgress_AssessmentModuleVersions_AssessmentModuleVer~" FOREIGN KEY ("AssessmentModuleVersionId") REFERENCES "AssessmentModuleVersions" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ModuleProgress_ExamTakerAssignments_ExamTakerAssignmentId" FOREIGN KEY ("ExamTakerAssignmentId") REFERENCES "ExamTakerAssignments" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ModuleProgress_GroupMembers_GroupMemberId" FOREIGN KEY ("GroupMemberId") REFERENCES "GroupMembers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE TABLE "PossibleAnswerEntityStaticFileEntity" (
        "AssociatedStaticFilesId" uuid NOT NULL,
        "PossibleAnswersId" uuid NOT NULL,
        CONSTRAINT "PK_PossibleAnswerEntityStaticFileEntity" PRIMARY KEY ("AssociatedStaticFilesId", "PossibleAnswersId"),
        CONSTRAINT "FK_PossibleAnswerEntityStaticFileEntity_AssessmentPossibleAnsw~" FOREIGN KEY ("PossibleAnswersId") REFERENCES "AssessmentPossibleAnswers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_PossibleAnswerEntityStaticFileEntity_StaticFiles_Associated~" FOREIGN KEY ("AssociatedStaticFilesId") REFERENCES "StaticFiles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE TABLE "QuestionResponses" (
        "Id" uuid NOT NULL,
        "SelectedAnswerIds" uuid[] NOT NULL,
        "TextResponse" text,
        "QuestionType" integer NOT NULL,
        "IsCorrect" boolean,
        "RespondedAtUtc" timestamp with time zone NOT NULL,
        "ModuleProgressId" uuid NOT NULL,
        "QuestionId" uuid NOT NULL,
        CONSTRAINT "PK_QuestionResponses" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_QuestionResponses_AssessmentQuestions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES "AssessmentQuestions" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_QuestionResponses_ModuleProgress_ModuleProgressId" FOREIGN KEY ("ModuleProgressId") REFERENCES "ModuleProgress" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    INSERT INTO "MessageTemplates" ("Id", "Body", "Name", "Subject")
    VALUES ('6863fdeb-ed8d-41ba-8567-c00cf8561470', '<!DOCTYPE html>
    <html lang="en" style="margin:0;padding:0;">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <meta name="x-apple-disable-message-reformatting" />
        <meta name="format-detection" content="telephone=no,address=no,email=no,date=no,url=no" />
        <meta name="color-scheme" content="light dark" />
        <meta name="supported-color-schemes" content="light dark" />
        <title>Welcome to PublicQ</title>
        <style>
          body {
            margin:0;
            padding:0;
            background:linear-gradient(135deg,#e6f0ff,#f9fbff);
            font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',Roboto,Ubuntu,''Helvetica Neue'',Arial,sans-serif;
            color:#1e2330;
          }
          .container {
            max-width:800px;
            margin:0 auto;
            padding:32px 20px;
          }
          .card {
            background:rgba(255,255,255,0.85);
            border-radius:16px;
            padding:32px;
            box-shadow:0 8px 20px rgba(0,0,0,0.1);
          }
          h1 {
            margin:0 0 20px 0;
            font-size:24px;
            font-weight:600;
            color:#0b5fff;
            text-align:center;
          }
          p {
            margin:0 0 16px 0;
            font-size:16px;
            line-height:1.6;
          }
          .cta {
            display:block;
            margin:20px auto 10px auto;
            width:max-content;
            text-decoration:none;
            background:#0b5fff;
            color:#ffffff !important;
            padding:12px 20px;
            border-radius:10px;
            font-weight:600;
          }
          .link-fallback {
            background:#f1f4fb;
            border-radius:8px;
            padding:12px 16px;
            margin:12px 0 0 0;
            font-family:monospace;
            font-size:14px;
            color:#0b5fff;
            word-break:break-all;
          }
          .footer {
            margin-top:28px;
            font-size:12px;
            color:#6b7280;
            text-align:center;
          }
          @media (max-width:600px) {
            .card { padding:20px; }
            h1 { font-size:20px; }
            p { font-size:15px; }
          }
          @media (prefers-color-scheme: dark) {
            body {
              background:linear-gradient(135deg,#0f1115,#1b1e24);
              color:#e7e7ea;
            }
            .card {
              background:rgba(30,33,40,0.85);
              border:1px solid #2a2f3a;
            }
            h1 { color:#7cb8ff; }
            .cta { background:#7cb8ff; color:#0f1115 !important; }
            .link-fallback { background:#252b36; color:#7cb8ff; }
            .footer { color:#a7acb8; }
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="card">
            <h1>Welcome to PublicQ</h1>
            <p>Hello <strong>{{User}}</strong>,</p>
            <p>
              Your account on <a href="{{BaseUrl}}" target="_blank" rel="noopener" style="color:#0b5fff;font-weight:600;text-decoration:none;">PublicQ</a> has been created successfully.  
              We’re glad to welcome you to the platform.
            </p>

            <!-- Primary CTA button -->
            <a class="cta" href="{{CreatePasswordUrl}}" target="_blank" rel="noopener">Create Your Password</a>

            <!-- Fallback plain link -->
            <div class="link-fallback">
              {{CreatePasswordUrl}}
            </div>

            <p style="margin-top:16px;">If you didn’t sign up for a PublicQ account, you can safely ignore this email.</p>
            <p>Best regards,<br/>PublicQ Team</p>

            <div class="footer">
              Your account is ready — let’s get started!
            </div>
          </div>
        </div>
      </body>
    </html>', 'Default Welcome Email with Create Password Link', 'Dear {{User}}, welcome to PublicQ!');
    INSERT INTO "MessageTemplates" ("Id", "Body", "Name", "Subject")
    VALUES ('a5091d38-fa5e-4cdb-b4bc-22381aeaf8be', '<!DOCTYPE html>
    <html lang="en" style="margin:0;padding:0;">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <meta name="x-apple-disable-message-reformatting" />
        <meta name="format-detection" content="telephone=no,address=no,email=no,date=no,url=no" />
        <meta name="color-scheme" content="light dark" />
        <meta name="supported-color-schemes" content="light dark" />
        <title>Reset Your Password</title>
        <style>
          body {
            margin:0;
            padding:0;
            background:linear-gradient(135deg,#e6f0ff,#f9fbff);
            font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',Roboto,Ubuntu,''Helvetica Neue'',Arial,sans-serif;
            color:#1e2330;
          }
          .container {
            max-width:800px;
            margin:0 auto;
            padding:32px 20px;
          }
          .card {
            background:rgba(255,255,255,0.85);
            border-radius:16px;
            padding:32px;
            box-shadow:0 8px 20px rgba(0,0,0,0.1);
          }
          h1 {
            margin:0 0 20px 0;
            font-size:24px;
            font-weight:600;
            color:#0b5fff;
            text-align:center;
          }
          p {
            margin:0 0 16px 0;
            font-size:16px;
            line-height:1.6;
          }
          .cta {
            display:block;
            margin:20px auto 10px auto;
            width:max-content;
            text-decoration:none;
            background:#0b5fff;
            color:#ffffff !important;
            padding:12px 20px;
            border-radius:10px;
            font-weight:600;
          }
          .link-fallback {
            background:#f1f4fb;
            border-radius:8px;
            padding:12px 16px;
            margin:12px 0 0 0;
            font-family:monospace;
            font-size:14px;
            color:#0b5fff;
            word-break:break-all;
          }
          .footer {
            margin-top:28px;
            font-size:12px;
            color:#6b7280;
            text-align:center;
          }
          @media (max-width:600px) {
            .card { padding:20px; }
            h1 { font-size:20px; }
            p { font-size:15px; }
          }
          @media (prefers-color-scheme: dark) {
            body {
              background:linear-gradient(135deg,#0f1115,#1b1e24);
              color:#e7e7ea;
            }
            .card {
              background:rgba(30,33,40,0.85);
              border:1px solid #2a2f3a;
            }
            h1 { color:#7cb8ff; }
            .link-fallback {
              background:#252b36;
              color:#7cb8ff;
            }
            .footer { color:#a7acb8; }
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="card">
            <h1>Reset Your Password</h1>
            <p>Hello <strong>{{User}}</strong>,</p>
            <p>We received a request to reset your password. Click the button below to create a new one:</p>

            <!-- Primary CTA uses the reset link -->
            <a class="cta" href="{{ResetLink}}" target="_blank" rel="noopener">Reset Password</a>

            <!-- Fallback plain link (placed under {{ResetLink}}) -->
            <div class="link-fallback">
              {{ResetLink}}
            </div>

            <p style="margin-top:16px;">If you didn’t request a password reset, you can safely ignore this email.</p>
            <p>Best regards,<br/>PublicQ Team</p>

            <div class="footer">
              This link will expire after a short period for security reasons.
            </div>
          </div>
        </div>
      </body>
    </html>', 'Default Forget Password', 'Dear {{User}}, here is your password reset link');
    INSERT INTO "MessageTemplates" ("Id", "Body", "Name", "Subject")
    VALUES ('bfc0e145-396f-4bc1-ae2f-14e528fe55b3', '<!DOCTYPE html>
    <html lang="en" style="margin:0;padding:0;">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <meta name="x-apple-disable-message-reformatting" />
        <meta name="format-detection" content="telephone=no,address=no,email=no,date=no,url=no" />
        <meta name="color-scheme" content="light dark" />
        <meta name="supported-color-schemes" content="light dark" />
        <title>Password Reset</title>
        <style>
          body {
            margin:0;
            padding:0;
            background:linear-gradient(135deg,#e6f0ff,#f9fbff);
            font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',Roboto,Ubuntu,''Helvetica Neue'',Arial,sans-serif;
            color:#1e2330;
          }
          .container {
            max-width:800px;
            margin:0 auto;
            padding:32px 20px;
          }
          .card {
            background:rgba(255,255,255,0.85);
            border-radius:16px;
            padding:32px;
            box-shadow:0 8px 20px rgba(0,0,0,0.1);
          }
          h1 {
            margin:0 0 20px 0;
            font-size:24px;
            font-weight:600;
            color:#0b5fff;
            text-align:center;
          }
          p {
            margin:0 0 16px 0;
            font-size:16px;
            line-height:1.6;
          }
          .password-box {
            background:#f1f4fb;
            border-radius:8px;
            padding:12px 16px;
            margin:16px 0;
            font-family:monospace;
            font-size:16px;
            font-weight:600;
            color:#0b5fff;
            text-align:center;
          }
          .footer {
            margin-top:28px;
            font-size:12px;
            color:#6b7280;
            text-align:center;
          }
          @media (max-width:600px) {
            .card { padding:20px; }
            h1 { font-size:20px; }
            p { font-size:15px; }
          }
          @media (prefers-color-scheme: dark) {
            body {
              background:linear-gradient(135deg,#0f1115,#1b1e24);
              color:#e7e7ea;
            }
            .card {
              background:rgba(30,33,40,0.85);
              border:1px solid #2a2f3a;
            }
            h1 { color:#7cb8ff; }
            .password-box {
              background:#252b36;
              color:#7cb8ff;
            }
            .footer { color:#a7acb8; }
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="card">
            <h1>Password Reset by Administrator</h1>
            <p>Hello <strong>{{User}}</strong>,</p>
            <p>
              Your password has been reset by the <strong>system administrator</strong>.  
            </p>
            <p>Here is your new password:</p>
            <div class="password-box">
              {{Password}}
            </div>
            <p>Best regards,<br/>PublicQ Team</p>
            <div class="footer">
              If you did not expect this reset, please contact support immediately.
            </div>
          </div>
        </div>
      </body>
    </html>', 'Default Password Reset Email', 'Dear {{User}}, your password has been reset');
    INSERT INTO "MessageTemplates" ("Id", "Body", "Name", "Subject")
    VALUES ('f2a1a4c8-8e6a-4f1c-b9f8-9f2c4c622dd9', '<!DOCTYPE html>
    <html lang="en" style="margin:0;padding:0;">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <meta name="x-apple-disable-message-reformatting" />
        <meta name="format-detection" content="telephone=no,address=no,email=no,date=no,url=no" />
        <meta name="color-scheme" content="light dark" />
        <meta name="supported-color-schemes" content="light dark" />
        <title>Welcome to PublicQ</title>
        <style>
          body {
            margin:0;
            padding:0;
            background:linear-gradient(135deg,#e6f0ff,#f9fbff);
            font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',Roboto,Ubuntu,''Helvetica Neue'',Arial,sans-serif;
            color:#1e2330;
          }
          .container {
            max-width:800px;
            margin:0 auto;
            padding:32px 20px;
          }
          .card {
            background:rgba(255,255,255,0.85);
            border-radius:16px;
            padding:32px;
            box-shadow:0 8px 20px rgba(0,0,0,0.1);
          }
          h1 {
            margin:0 0 20px 0;
            font-size:24px;
            font-weight:600;
            color:#0b5fff;
            text-align:center;
          }
          p {
            margin:0 0 16px 0;
            font-size:16px;
            line-height:1.6;
          }
          .footer {
            margin-top:28px;
            font-size:12px;
            color:#6b7280;
            text-align:center;
          }
          @media (max-width:600px) {
            .card { padding:20px; }
            h1 { font-size:20px; }
            p { font-size:15px; }
          }
          @media (prefers-color-scheme: dark) {
            body {
              background:linear-gradient(135deg,#0f1115,#1b1e24);
              color:#e7e7ea;
            }
            .card {
              background:rgba(30,33,40,0.85);
              border:1px solid #2a2f3a;
            }
            h1 { color:#7cb8ff; }
            .footer { color:#a7acb8; }
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="card">
            <h1>Welcome to PublicQ</h1>
            <p>Hello <strong>{{User}}</strong>,</p>
            <p>
              Thank you for joining <span style="color:#0b5fff;font-weight:600;">PublicQ</span>!  
              We are excited to have you on board.
            </p>
            <p>Best regards,<br/>PublicQ Team</p>
            <div class="footer">
              If you did not create a PublicQ account, you can safely ignore this message.
            </div>
          </div>
        </div>
      </body>
    </html>', 'Default Welcome Email', 'Dear {{User}}, welcome to PublicQ!');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('AssessmentServiceOptions:MaxPageSize', '100');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('AssignmentServiceOptions:MaxPageSize', '100');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('AuthOptions:JwtSettings:Audience', 'PublicQClient');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('AuthOptions:JwtSettings:Issuer', 'PublicQServer');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('AuthOptions:JwtSettings:Secret', 'ChangeMe:VGhpc0lzQVNlY3VyZURlZmF1bHRKV1RTZWNyZXRLZXlGb3JEZXZlbG9wbWVudFB1cnBvc2VzT25seQ==');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('AuthOptions:JwtSettings:TokenExpiryMinutes', '60');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('DbLoggerOptions:Enabled', 'true');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('DbLoggerOptions:ExcludedCategories:0', 'PublicQ.Infrastructure.DynamicJwtBearerHandler');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('DbLoggerOptions:ExcludedCategories:1', 'Microsoft');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('DbLoggerOptions:ExcludedCategories:2', 'System');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('DbLoggerOptions:LogLevel', 'Error');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('DbLoggerOptions:MaxPageSize', '100');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('DbLoggerOptions:RetentionPeriodInDays', '90');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('EmailOptions:MessageProvider', 'Sendgrid');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('EmailOptions:SendFrom', 'change-me@publiq.local');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('FileStorageOptions:MaxUploadFileSizeInKilobytes', '5120');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('FileStorageOptions:StaticContentPath', 'static');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('GroupServiceOptions:MaxPageSize', '100');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('InitialSetupOptions:IsInitialized', 'false');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('IpRateLimitOptions:GeneralRules:0:Endpoint', '*');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('IpRateLimitOptions:GeneralRules:0:Limit', '100');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('IpRateLimitOptions:GeneralRules:0:Period', '10s');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('IpRateLimitOptions:IpWhitelist:0', '127.0.0.1');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('IpRateLimitOptions:IpWhitelist:1', '::1');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('IpRateLimitOptions:RealIpHeader', 'X-Forwarded-For');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('LlmIntegrationOptions:Enabled', 'false');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('LlmIntegrationOptions:Provider', 'OpenAI');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('PasswordPolicyOptions:RequireDigit', 'true');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('PasswordPolicyOptions:RequireLowercase', 'true');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('PasswordPolicyOptions:RequireNonAlphanumeric', 'false');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('PasswordPolicyOptions:RequireUppercase', 'true');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('PasswordPolicyOptions:RequiredLength', '8');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('RedisOptions:AbortOnConnectFail', 'false');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('RedisOptions:ConnectionString', 'redis:6379');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('RedisOptions:DefaultDurationInMinutes', '60');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('RedisOptions:Enabled', 'false');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('RedisOptions:KeyPrefix', 'PublicQ:');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('RedisOptions:ServiceDurationsInMinutes:IReportingService', '60');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('ReportingServiceOptions:MaxPageSize', '100');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('SendgridOptions:ApiKey', '<Your Sendgrid API Key>');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('SmtpOptions:SmtpHost', 'localhost');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('SmtpOptions:SmtpPort', '25');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('SmtpOptions:UseSsl', 'false');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('SmtpOptions:UseStartTls', 'false');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('UserServiceOptions:MaxImportSize', '500');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('UserServiceOptions:MaxPageSize', '100');
    INSERT INTO "SystemSettings" ("Name", "Value")
    VALUES ('UserServiceOptions:SelfServiceRegistrationEnabled', 'true');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE INDEX "IX_AssessmentModuleVersions_AssessmentModuleId" ON "AssessmentModuleVersions" ("AssessmentModuleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE INDEX "IX_AssessmentModuleVersions_NormalizedTitle" ON "AssessmentModuleVersions" ("NormalizedTitle");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE INDEX "IX_AssessmentModuleVersions_Title" ON "AssessmentModuleVersions" ("Title");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE INDEX "IX_AssessmentPossibleAnswers_QuestionId" ON "AssessmentPossibleAnswers" ("QuestionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE INDEX "IX_AssessmentQuestions_AssessmentModuleVersionId" ON "AssessmentQuestions" ("AssessmentModuleVersionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE INDEX "IX_Assignments_GroupId" ON "Assignments" ("GroupId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Assignments_Title" ON "Assignments" ("Title");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE INDEX "IX_Banners_ShowToAuthenticatedUsersOnly" ON "Banners" ("ShowToAuthenticatedUsersOnly");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE INDEX "IX_ExamTakerAssignments_AssignmentId" ON "ExamTakerAssignments" ("AssignmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_ExamTakers_NormalizedEmail" ON "ExamTakers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE INDEX "IX_GroupMembers_AssessmentModuleId" ON "GroupMembers" ("AssessmentModuleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_GroupMembers_GroupId_OrderNumber" ON "GroupMembers" ("GroupId", "OrderNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Groups_NormalizedTitle" ON "Groups" ("NormalizedTitle");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE INDEX "IX_LogEntries_Level" ON "LogEntries" ("Level");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE INDEX "IX_LogEntries_Timestamp" ON "LogEntries" ("Timestamp");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE INDEX "IX_ModuleProgress_AssessmentModuleVersionId" ON "ModuleProgress" ("AssessmentModuleVersionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE INDEX "IX_ModuleProgress_ExamTakerAssignmentId" ON "ModuleProgress" ("ExamTakerAssignmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE INDEX "IX_ModuleProgress_GroupMemberId" ON "ModuleProgress" ("GroupMemberId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE INDEX "IX_PossibleAnswerEntityStaticFileEntity_PossibleAnswersId" ON "PossibleAnswerEntityStaticFileEntity" ("PossibleAnswersId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE INDEX "IX_QuestionEntityStaticFileEntity_QuestionsId" ON "QuestionEntityStaticFileEntity" ("QuestionsId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE INDEX "IX_QuestionResponses_ModuleProgressId" ON "QuestionResponses" ("ModuleProgressId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE INDEX "IX_QuestionResponses_QuestionId" ON "QuestionResponses" ("QuestionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE INDEX "IX_StaticFiles_AssessmentModuleId" ON "StaticFiles" ("AssessmentModuleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    CREATE INDEX "IX_StaticFiles_AssessmentModuleVersionEntityId" ON "StaticFiles" ("AssessmentModuleVersionEntityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260311210720_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260311210720_InitialCreate', '9.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312131506_AddAdmissionNumber') THEN
    ALTER TABLE "ExamTakers" ADD "AdmissionNumber" character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312131506_AddAdmissionNumber') THEN
    ALTER TABLE "AspNetUsers" ADD "AdmissionNumber" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312131506_AddAdmissionNumber') THEN
    UPDATE "MessageTemplates" SET "Body" = '<!DOCTYPE html>
    <html lang="en" style="margin:0;padding:0;">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <meta name="x-apple-disable-message-reformatting" />
        <meta name="format-detection" content="telephone=no,address=no,email=no,date=no,url=no" />
        <meta name="color-scheme" content="light dark" />
        <meta name="supported-color-schemes" content="light dark" />
        <title>Welcome to ExamNova</title>
        <style>
          body {
            margin:0;
            padding:0;
            background:linear-gradient(135deg,#e6f0ff,#f9fbff);
            font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',Roboto,Ubuntu,''Helvetica Neue'',Arial,sans-serif;
            color:#1e2330;
          }
          .container {
            max-width:800px;
            margin:0 auto;
            padding:32px 20px;
          }
          .card {
            background:rgba(255,255,255,0.85);
            border-radius:16px;
            padding:32px;
            box-shadow:0 8px 20px rgba(0,0,0,0.1);
          }
          h1 {
            margin:0 0 20px 0;
            font-size:24px;
            font-weight:600;
            color:#0b5fff;
            text-align:center;
          }
          p {
            margin:0 0 16px 0;
            font-size:16px;
            line-height:1.6;
          }
          .cta {
            display:block;
            margin:20px auto 10px auto;
            width:max-content;
            text-decoration:none;
            background:#0b5fff;
            color:#ffffff !important;
            padding:12px 20px;
            border-radius:10px;
            font-weight:600;
          }
          .link-fallback {
            background:#f1f4fb;
            border-radius:8px;
            padding:12px 16px;
            margin:12px 0 0 0;
            font-family:monospace;
            font-size:14px;
            color:#0b5fff;
            word-break:break-all;
          }
          .footer {
            margin-top:28px;
            font-size:12px;
            color:#6b7280;
            text-align:center;
          }
          @media (max-width:600px) {
            .card { padding:20px; }
            h1 { font-size:20px; }
            p { font-size:15px; }
          }
          @media (prefers-color-scheme: dark) {
            body {
              background:linear-gradient(135deg,#0f1115,#1b1e24);
              color:#e7e7ea;
            }
            .card {
              background:rgba(30,33,40,0.85);
              border:1px solid #2a2f3a;
            }
            h1 { color:#7cb8ff; }
            .cta { background:#7cb8ff; color:#0f1115 !important; }
            .link-fallback { background:#252b36; color:#7cb8ff; }
            .footer { color:#a7acb8; }
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="card">
            <h1>Welcome to ExamNova</h1>
            <p>Hello <strong>{{User}}</strong>,</p>
            <p>
              Your account on <a href="{{BaseUrl}}" target="_blank" rel="noopener" style="color:#0b5fff;font-weight:600;text-decoration:none;">ExamNova</a> has been created successfully.  
              We’re glad to welcome you to the platform.
            </p>

            <!-- Primary CTA button -->
            <a class="cta" href="{{CreatePasswordUrl}}" target="_blank" rel="noopener">Create Your Password</a>

            <!-- Fallback plain link -->
            <div class="link-fallback">
              {{CreatePasswordUrl}}
            </div>

            <p style="margin-top:16px;">If you didn’t sign up for a ExamNova account, you can safely ignore this email.</p>
            <p>Best regards,<br/>ExamNova Team</p>

            <div class="footer">
              Your account is ready — let’s get started!
            </div>
          </div>
        </div>
      </body>
    </html>', "Subject" = 'Dear {{User}}, welcome to ExamNova!'
    WHERE "Id" = '6863fdeb-ed8d-41ba-8567-c00cf8561470';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312131506_AddAdmissionNumber') THEN
    UPDATE "MessageTemplates" SET "Body" = '<!DOCTYPE html>
    <html lang="en" style="margin:0;padding:0;">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <meta name="x-apple-disable-message-reformatting" />
        <meta name="format-detection" content="telephone=no,address=no,email=no,date=no,url=no" />
        <meta name="color-scheme" content="light dark" />
        <meta name="supported-color-schemes" content="light dark" />
        <title>Reset Your Password</title>
        <style>
          body {
            margin:0;
            padding:0;
            background:linear-gradient(135deg,#e6f0ff,#f9fbff);
            font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',Roboto,Ubuntu,''Helvetica Neue'',Arial,sans-serif;
            color:#1e2330;
          }
          .container {
            max-width:800px;
            margin:0 auto;
            padding:32px 20px;
          }
          .card {
            background:rgba(255,255,255,0.85);
            border-radius:16px;
            padding:32px;
            box-shadow:0 8px 20px rgba(0,0,0,0.1);
          }
          h1 {
            margin:0 0 20px 0;
            font-size:24px;
            font-weight:600;
            color:#0b5fff;
            text-align:center;
          }
          p {
            margin:0 0 16px 0;
            font-size:16px;
            line-height:1.6;
          }
          .cta {
            display:block;
            margin:20px auto 10px auto;
            width:max-content;
            text-decoration:none;
            background:#0b5fff;
            color:#ffffff !important;
            padding:12px 20px;
            border-radius:10px;
            font-weight:600;
          }
          .link-fallback {
            background:#f1f4fb;
            border-radius:8px;
            padding:12px 16px;
            margin:12px 0 0 0;
            font-family:monospace;
            font-size:14px;
            color:#0b5fff;
            word-break:break-all;
          }
          .footer {
            margin-top:28px;
            font-size:12px;
            color:#6b7280;
            text-align:center;
          }
          @media (max-width:600px) {
            .card { padding:20px; }
            h1 { font-size:20px; }
            p { font-size:15px; }
          }
          @media (prefers-color-scheme: dark) {
            body {
              background:linear-gradient(135deg,#0f1115,#1b1e24);
              color:#e7e7ea;
            }
            .card {
              background:rgba(30,33,40,0.85);
              border:1px solid #2a2f3a;
            }
            h1 { color:#7cb8ff; }
            .link-fallback {
              background:#252b36;
              color:#7cb8ff;
            }
            .footer { color:#a7acb8; }
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="card">
            <h1>Reset Your Password</h1>
            <p>Hello <strong>{{User}}</strong>,</p>
            <p>We received a request to reset your password. Click the button below to create a new one:</p>

            <!-- Primary CTA uses the reset link -->
            <a class="cta" href="{{ResetLink}}" target="_blank" rel="noopener">Reset Password</a>

            <!-- Fallback plain link (placed under {{ResetLink}}) -->
            <div class="link-fallback">
              {{ResetLink}}
            </div>

            <p style="margin-top:16px;">If you didn’t request a password reset, you can safely ignore this email.</p>
            <p>Best regards,<br/>ExamNova Team</p>

            <div class="footer">
              This link will expire after a short period for security reasons.
            </div>
          </div>
        </div>
      </body>
    </html>'
    WHERE "Id" = 'a5091d38-fa5e-4cdb-b4bc-22381aeaf8be';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312131506_AddAdmissionNumber') THEN
    UPDATE "MessageTemplates" SET "Body" = '<!DOCTYPE html>
    <html lang="en" style="margin:0;padding:0;">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <meta name="x-apple-disable-message-reformatting" />
        <meta name="format-detection" content="telephone=no,address=no,email=no,date=no,url=no" />
        <meta name="color-scheme" content="light dark" />
        <meta name="supported-color-schemes" content="light dark" />
        <title>Password Reset</title>
        <style>
          body {
            margin:0;
            padding:0;
            background:linear-gradient(135deg,#e6f0ff,#f9fbff);
            font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',Roboto,Ubuntu,''Helvetica Neue'',Arial,sans-serif;
            color:#1e2330;
          }
          .container {
            max-width:800px;
            margin:0 auto;
            padding:32px 20px;
          }
          .card {
            background:rgba(255,255,255,0.85);
            border-radius:16px;
            padding:32px;
            box-shadow:0 8px 20px rgba(0,0,0,0.1);
          }
          h1 {
            margin:0 0 20px 0;
            font-size:24px;
            font-weight:600;
            color:#0b5fff;
            text-align:center;
          }
          p {
            margin:0 0 16px 0;
            font-size:16px;
            line-height:1.6;
          }
          .password-box {
            background:#f1f4fb;
            border-radius:8px;
            padding:12px 16px;
            margin:16px 0;
            font-family:monospace;
            font-size:16px;
            font-weight:600;
            color:#0b5fff;
            text-align:center;
          }
          .footer {
            margin-top:28px;
            font-size:12px;
            color:#6b7280;
            text-align:center;
          }
          @media (max-width:600px) {
            .card { padding:20px; }
            h1 { font-size:20px; }
            p { font-size:15px; }
          }
          @media (prefers-color-scheme: dark) {
            body {
              background:linear-gradient(135deg,#0f1115,#1b1e24);
              color:#e7e7ea;
            }
            .card {
              background:rgba(30,33,40,0.85);
              border:1px solid #2a2f3a;
            }
            h1 { color:#7cb8ff; }
            .password-box {
              background:#252b36;
              color:#7cb8ff;
            }
            .footer { color:#a7acb8; }
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="card">
            <h1>Password Reset by Administrator</h1>
            <p>Hello <strong>{{User}}</strong>,</p>
            <p>
              Your password has been reset by the <strong>system administrator</strong>.  
            </p>
            <p>Here is your new password:</p>
            <div class="password-box">
              {{Password}}
            </div>
            <p>Best regards,<br/>ExamNova Team</p>
            <div class="footer">
              If you did not expect this reset, please contact support immediately.
            </div>
          </div>
        </div>
      </body>
    </html>'
    WHERE "Id" = 'bfc0e145-396f-4bc1-ae2f-14e528fe55b3';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312131506_AddAdmissionNumber') THEN
    UPDATE "MessageTemplates" SET "Body" = '<!DOCTYPE html>
    <html lang="en" style="margin:0;padding:0;">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <meta name="x-apple-disable-message-reformatting" />
        <meta name="format-detection" content="telephone=no,address=no,email=no,date=no,url=no" />
        <meta name="color-scheme" content="light dark" />
        <meta name="supported-color-schemes" content="light dark" />
        <title>Welcome to ExamNova</title>
        <style>
          body {
            margin:0;
            padding:0;
            background:linear-gradient(135deg,#e6f0ff,#f9fbff);
            font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',Roboto,Ubuntu,''Helvetica Neue'',Arial,sans-serif;
            color:#1e2330;
          }
          .container {
            max-width:800px;
            margin:0 auto;
            padding:32px 20px;
          }
          .card {
            background:rgba(255,255,255,0.85);
            border-radius:16px;
            padding:32px;
            box-shadow:0 8px 20px rgba(0,0,0,0.1);
          }
          h1 {
            margin:0 0 20px 0;
            font-size:24px;
            font-weight:600;
            color:#0b5fff;
            text-align:center;
          }
          p {
            margin:0 0 16px 0;
            font-size:16px;
            line-height:1.6;
          }
          .footer {
            margin-top:28px;
            font-size:12px;
            color:#6b7280;
            text-align:center;
          }
          @media (max-width:600px) {
            .card { padding:20px; }
            h1 { font-size:20px; }
            p { font-size:15px; }
          }
          @media (prefers-color-scheme: dark) {
            body {
              background:linear-gradient(135deg,#0f1115,#1b1e24);
              color:#e7e7ea;
            }
            .card {
              background:rgba(30,33,40,0.85);
              border:1px solid #2a2f3a;
            }
            h1 { color:#7cb8ff; }
            .footer { color:#a7acb8; }
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="card">
            <h1>Welcome to ExamNova</h1>
            <p>Hello <strong>{{User}}</strong>,</p>
            <p>
              Thank you for joining <span style="color:#0b5fff;font-weight:600;">ExamNova</span>!  
              We are excited to have you on board.
            </p>
            <p>Best regards,<br/>ExamNova Team</p>
            <div class="footer">
              If you did not create a ExamNova account, you can safely ignore this message.
            </div>
          </div>
        </div>
      </body>
    </html>', "Subject" = 'Dear {{User}}, welcome to ExamNova!'
    WHERE "Id" = 'f2a1a4c8-8e6a-4f1c-b9f8-9f2c4c622dd9';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312131506_AddAdmissionNumber') THEN
    UPDATE "SystemSettings" SET "Value" = 'ExamNovaClient'
    WHERE "Name" = 'AuthOptions:JwtSettings:Audience';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312131506_AddAdmissionNumber') THEN
    UPDATE "SystemSettings" SET "Value" = 'ExamNovaServer'
    WHERE "Name" = 'AuthOptions:JwtSettings:Issuer';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312131506_AddAdmissionNumber') THEN
    UPDATE "SystemSettings" SET "Value" = 'no-reply@examnova.local'
    WHERE "Name" = 'EmailOptions:SendFrom';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312131506_AddAdmissionNumber') THEN
    UPDATE "SystemSettings" SET "Value" = 'ExamNova:'
    WHERE "Name" = 'RedisOptions:KeyPrefix';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312131506_AddAdmissionNumber') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260312131506_AddAdmissionNumber', '9.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312153023_AddAdmissionNumberSeed') THEN
    UPDATE "ExamTakers" SET "DateOfBirth" = TIMESTAMPTZ '-infinity' WHERE "DateOfBirth" IS NULL;
    ALTER TABLE "ExamTakers" ALTER COLUMN "DateOfBirth" SET NOT NULL;
    ALTER TABLE "ExamTakers" ALTER COLUMN "DateOfBirth" SET DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312153023_AddAdmissionNumberSeed') THEN
    UPDATE "AspNetUsers" SET "DateOfBirth" = TIMESTAMPTZ '-infinity' WHERE "DateOfBirth" IS NULL;
    ALTER TABLE "AspNetUsers" ALTER COLUMN "DateOfBirth" SET NOT NULL;
    ALTER TABLE "AspNetUsers" ALTER COLUMN "DateOfBirth" SET DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312153023_AddAdmissionNumberSeed') THEN
    INSERT INTO "UserConfigurations" ("Id", "DataJson", "Type")
    VALUES (1, '{
      "Format": "EN-{YYYY}-{0000}",
      "LastSequenceNumber": 0
    }', 1);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312153023_AddAdmissionNumberSeed') THEN
    PERFORM setval(
        pg_get_serial_sequence('"UserConfigurations"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "UserConfigurations") + 1,
            nextval(pg_get_serial_sequence('"UserConfigurations"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312153023_AddAdmissionNumberSeed') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260312153023_AddAdmissionNumberSeed', '9.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312212731_Phase5AcademicCore') THEN
    ALTER TABLE "ExamTakers" ALTER COLUMN "DateOfBirth" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312212731_Phase5AcademicCore') THEN
    ALTER TABLE "AspNetUsers" ALTER COLUMN "DateOfBirth" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312212731_Phase5AcademicCore') THEN
    CREATE TABLE "ClassLevels" (
        "Id" uuid NOT NULL,
        "Name" character varying(100) NOT NULL,
        "SectionOrArm" character varying(50),
        "OrderIndex" integer NOT NULL,
        CONSTRAINT "PK_ClassLevels" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312212731_Phase5AcademicCore') THEN
    CREATE TABLE "Sessions" (
        "Id" uuid NOT NULL,
        "Name" character varying(100) NOT NULL,
        "StartDate" timestamp with time zone,
        "EndDate" timestamp with time zone,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_Sessions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312212731_Phase5AcademicCore') THEN
    CREATE TABLE "Subjects" (
        "Id" uuid NOT NULL,
        "Name" character varying(150) NOT NULL,
        "Code" character varying(50),
        "DisplayOrder" integer NOT NULL,
        CONSTRAINT "PK_Subjects" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312212731_Phase5AcademicCore') THEN
    CREATE TABLE "Terms" (
        "Id" uuid NOT NULL,
        "SessionId" uuid NOT NULL,
        "Name" character varying(100) NOT NULL,
        "StartDate" timestamp with time zone,
        "EndDate" timestamp with time zone,
        "NextTermBegins" timestamp with time zone,
        "NextTermBills" character varying(200),
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_Terms" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Terms_Sessions_SessionId" FOREIGN KEY ("SessionId") REFERENCES "Sessions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312212731_Phase5AcademicCore') THEN
    CREATE TABLE "StudentAssessments" (
        "Id" uuid NOT NULL,
        "ExamTakerId" text NOT NULL,
        "SessionId" uuid NOT NULL,
        "TermId" uuid NOT NULL,
        "ClassLevelId" uuid NOT NULL,
        "Status" integer NOT NULL,
        "IsLockedForParents" boolean NOT NULL,
        "TotalMarksObtained" numeric,
        "TotalMarksObtainable" numeric,
        "AverageScore" numeric,
        "PositionInClass" integer,
        "NumberInClass" integer,
        "OverallGrade" character varying(5),
        "TimesSchoolOpened" integer,
        "TimesPresent" integer,
        "TimesAbsent" integer,
        "Regularity" character varying(10),
        "Punctuality" character varying(10),
        "Neatness" character varying(10),
        "AttitudeInSchool" character varying(10),
        "SocialActivities" character varying(10),
        "IndoorGames" character varying(10),
        "FieldGames" character varying(10),
        "TrackGames" character varying(10),
        "Jumps" character varying(10),
        "Swims" character varying(10),
        "ClassTeacherComment" character varying(500),
        "HeadTeacherComment" character varying(500),
        "CreatedAt" timestamp with time zone NOT NULL,
        "PublishedAt" timestamp with time zone,
        CONSTRAINT "PK_StudentAssessments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_StudentAssessments_ClassLevels_ClassLevelId" FOREIGN KEY ("ClassLevelId") REFERENCES "ClassLevels" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_StudentAssessments_ExamTakers_ExamTakerId" FOREIGN KEY ("ExamTakerId") REFERENCES "ExamTakers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_StudentAssessments_Sessions_SessionId" FOREIGN KEY ("SessionId") REFERENCES "Sessions" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_StudentAssessments_Terms_TermId" FOREIGN KEY ("TermId") REFERENCES "Terms" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312212731_Phase5AcademicCore') THEN
    CREATE TABLE "SubjectScores" (
        "Id" uuid NOT NULL,
        "StudentAssessmentId" uuid NOT NULL,
        "SubjectId" uuid NOT NULL,
        "TestScore" numeric,
        "ExamScore" numeric,
        "TotalScore" numeric,
        "Grade" character varying(5),
        "SubjectRemark" character varying(100),
        CONSTRAINT "PK_SubjectScores" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SubjectScores_StudentAssessments_StudentAssessmentId" FOREIGN KEY ("StudentAssessmentId") REFERENCES "StudentAssessments" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_SubjectScores_Subjects_SubjectId" FOREIGN KEY ("SubjectId") REFERENCES "Subjects" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312212731_Phase5AcademicCore') THEN
    CREATE UNIQUE INDEX "IX_ClassLevels_Name_SectionOrArm" ON "ClassLevels" ("Name", "SectionOrArm");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312212731_Phase5AcademicCore') THEN
    CREATE UNIQUE INDEX "IX_Sessions_Name" ON "Sessions" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312212731_Phase5AcademicCore') THEN
    CREATE INDEX "IX_StudentAssessments_ClassLevelId" ON "StudentAssessments" ("ClassLevelId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312212731_Phase5AcademicCore') THEN
    CREATE UNIQUE INDEX "IX_StudentAssessments_ExamTakerId_SessionId_TermId" ON "StudentAssessments" ("ExamTakerId", "SessionId", "TermId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312212731_Phase5AcademicCore') THEN
    CREATE INDEX "IX_StudentAssessments_SessionId" ON "StudentAssessments" ("SessionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312212731_Phase5AcademicCore') THEN
    CREATE INDEX "IX_StudentAssessments_TermId" ON "StudentAssessments" ("TermId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312212731_Phase5AcademicCore') THEN
    CREATE UNIQUE INDEX "IX_SubjectScores_StudentAssessmentId_SubjectId" ON "SubjectScores" ("StudentAssessmentId", "SubjectId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312212731_Phase5AcademicCore') THEN
    CREATE INDEX "IX_SubjectScores_SubjectId" ON "SubjectScores" ("SubjectId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312212731_Phase5AcademicCore') THEN
    CREATE UNIQUE INDEX "IX_Subjects_Name" ON "Subjects" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312212731_Phase5AcademicCore') THEN
    CREATE INDEX "IX_Terms_SessionId" ON "Terms" ("SessionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312212731_Phase5AcademicCore') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260312212731_Phase5AcademicCore', '9.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260318080017_AddPermissions') THEN
    CREATE TABLE "ParentStudentLinks" (
        "Id" uuid NOT NULL,
        "ParentId" text NOT NULL,
        "StudentId" text NOT NULL,
        "Relationship" character varying(50),
        CONSTRAINT "PK_ParentStudentLinks" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ParentStudentLinks_AspNetUsers_ParentId" FOREIGN KEY ("ParentId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ParentStudentLinks_ExamTakers_StudentId" FOREIGN KEY ("StudentId") REFERENCES "ExamTakers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260318080017_AddPermissions') THEN
    CREATE TABLE "Permissions" (
        "Id" uuid NOT NULL,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(250) NOT NULL,
        CONSTRAINT "PK_Permissions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260318080017_AddPermissions') THEN
    CREATE TABLE "RolePermissionLinks" (
        "RoleId" text NOT NULL,
        "PermissionId" uuid NOT NULL,
        CONSTRAINT "PK_RolePermissionLinks" PRIMARY KEY ("RoleId", "PermissionId"),
        CONSTRAINT "FK_RolePermissionLinks_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_RolePermissionLinks_Permissions_PermissionId" FOREIGN KEY ("PermissionId") REFERENCES "Permissions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260318080017_AddPermissions') THEN
    CREATE UNIQUE INDEX "IX_ParentStudentLinks_ParentId_StudentId" ON "ParentStudentLinks" ("ParentId", "StudentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260318080017_AddPermissions') THEN
    CREATE INDEX "IX_ParentStudentLinks_StudentId" ON "ParentStudentLinks" ("StudentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260318080017_AddPermissions') THEN
    CREATE UNIQUE INDEX "IX_Permissions_Name" ON "Permissions" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260318080017_AddPermissions') THEN
    CREATE INDEX "IX_RolePermissionLinks_PermissionId" ON "RolePermissionLinks" ("PermissionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260318080017_AddPermissions') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260318080017_AddPermissions', '9.0.0');
    END IF;
END $EF$;
COMMIT;

